// THIS FILE IS SOME CUSTOMIZATION FOR YOUR OWN USE.
// READ THE COMMENTS BEFORE CHANGING THE VALUE OF CONSTANTS.
// ----------------------------------------------------------------

// THIS IS THE COUNT-DOWN REFRESH TIME.
// THE VALUE SMALLER, THE COUNT-DOWN WILL BE MORE PRECISE.
// UNIT: ms (milliseconds)
// DEFAULT: 500
const COUNT_DOWN_INTERVAL = 500;

// THIS IS THE TIME LIMIT.
// FORMAT: (for example) "July 25, 2022, 12:00:00"
// DEFAULT: "July 25, 2022, 12:00:00"
const TIME_LIMIT = "July 25, 2022, 12:00:00";

// THIS IS THE TITLE OF THE COUNT-DOWN PAGE.
// DEFAULT: "两周年倒计时—— czm & ltx"
const COUNT_DOWN_TITLE = "两周年倒计时—— czm & ltx";

// THIS MESSAGE WILL BE SHOWED IF THE TIME LIMIT EXCEEDED.
// DEFAULT: "- 0 - 0 - 0 - 0 -"
const COUNT_DOWN_DONE_MESSAGE = "- 0 - 0 - 0 - 0 -";

// THIS VARIABLE DETERMINES IF THE SNOW-FALLING EFFECT IS ENABLED OR NOT.
// DEFAULT: true
const DO_SNOW_FALL_ENABLED = true;

// THIS VARIABL DETERMINES THE BACKGROUND IMAGE.
// DEFAULT: null
const BACKGROUND_IMAGE = null;
